"""Per-repository template for tools/build_notebook.py (NOTEBOOK_SPEC 2.2 §4 standalone carrier).

Only the task-specific prose and stage cells live here. Runtime install, the embedded pipeline
modules (pipeline.py, metrics.py, samples.py), and the model pin/stage/verify cells are produced by
the generator from repository sources so they cannot drift from the package.

This template configures an E2E image-captioning workflow: the pinned Salesforce/blip-image-captioning-base
snapshot is digest-verified and loaded, the captions of a digest-pinned VizWiz-Captions shard are read
column-only and the 336 photographs of its first row group are read the same way, validated and split by
image, three drawn scenes are captioned through the inference contract, the frozen model is scored on the
held-out photographs beside two non-neural baselines, a bounded fine-tuning of the caption decoder's last
blocks runs, the held-out split is scored again per category, the adapted model re-captions the drawn
scenes, and the adapter is exported and reloaded.

Review fixes (Notebook Review Framework v1, review PR #7, CAP-M1..M5 / CAP-m1..m3): the runtime is the fleet's uv
isolated environment (no in-kernel install, no restart); no held-out result is asserted, and the notebook says
that the default hyperparameters were chosen with the test split, so the test gain is optimistic; every re-run of
Sections 5-7 starts from the pretrained model; the BYOD contract states the enforced minimum, replaces an earlier
upload, keeps zip sub-folders under a guarded root with size limits, names a missing records file and records BYOD
provenance; and the guided layer (how to use, roadmap, predictions, worked answers, a change-one-thing activity,
troubleshooting, glossary, conclusion) is added.
"""
# ruff: noqa: E501  -- markdown prose and code-cell text are kept on single lines for readable rendering

TEMPLATE = {
    "package": "blip_captioning_pipeline",
    "repo_name": "blip-captioning-pipeline",
    "stem": "blip_captioning",
    "notebook_name": "blip_captioning_colab.ipynb",
    "profile": "E2E",
    "mode": "GUIDED",
    "infrastructure_labels": True,
    "isolated_runtime": True,
    # The fleet's uv isolated-environment mechanism (ast-audio-classification-pipeline / bioclip2-biodiversity-pipeline):
    # managed CPython, a size- and SHA-256-verified uv wheel, and a lock compiled from the pyproject pins with
    # `uv pip compile pyproject.toml --python-version 3.12 --python-platform x86_64-manylinux_2_28 --generate-hashes
    # --only-binary :all: -o tutorials/requirements-colab.lock.txt`.
    "managed_python": "3.12.12",
    "uv": {
        "version": "0.12.15",
        "url": "https://files.pythonhosted.org/packages/1e/fd/432451d732917c49152a291de3ef171aa6b0f1a22d39780fb2c1f085ca4c/uv-0.12.15-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        "bytes": 20081404,
        "sha256": "aee9802f46bae436bd91751bb33ddeb379ef1596b5c19df193219d545d244b60",
    },
    "lock": "tutorials/requirements-colab.lock.txt",
    "run_all": (
        "Selecting **Run all** in a fresh supported runtime builds an isolated environment from the hash-locked pins (the "
        "kernel's own packages are left alone, so no restart is needed), stages and digest-verifies the "
        "pinned `Salesforce/blip-image-captioning-base` snapshot (a 990 MB `pytorch_model.bin` pickle, opened only after its "
        "SHA-256 matches and with `weights_only=True`), reads the four text columns of one digest-pinned VizWiz-Captions shard "
        "from the Hugging Face Hub (about 0.5 MB over HTTP range requests, no credential) and the image column of its first row "
        "group (336 photographs, about 84 MB, each refused on any size or SHA-256 mismatch), cuts the 318 captioned ones by "
        "image into 208 / 40 / 70 training, validation and test photographs, captions three drawn scenes through the inference "
        "contract with an input manifest and a rejection probe, scores the frozen model on the test photographs with BLEU-4, "
        "ROUGE-L, CIDEr-D and unigram F1 beside the constant-caption and colour-nearest-neighbour baselines, runs a bounded "
        "fine-tuning of the caption decoder's last blocks and head on the training photographs with validation-CIDEr-D epoch "
        "selection, scores the held-out photographs again per category, re-captions the drawn scenes with the adapted model, "
        "exports the adapter as safetensors with a manifest, and reloads that artifact into a fresh pipeline to verify caption "
        "parity. The default path needs no repository clone, no DIMER worker or service, no credential, no upload dialog and "
        "no configuration edit (NOTEBOOK_SPEC 2.2 §5). A CUDA runtime is used automatically when present. Measured times come "
        "from runs of the previous notebook version, whose model stages are the same: a local Windows CPU pre-flight "
        "(2026-09-19, float32, files pre-staged) took 879 s for the default path, and the Kaggle Tesla T4 run of 2026-09-19 "
        "took 439 s including the downloads. No hosted CPU run is recorded, so on a hosted CPU runtime expect roughly the CPU "
        "pre-flight figure (an estimate). Building the isolated environment and downloading the checkpoint come on top of these."
    ),
    "byod": (
        "After the tutorial workflow completes, set `USE_BYOD = True` in Section 4, select that cell and choose **Runtime → "
        "Run after** (it re-runs Section 4 and every later cell; Sections 5, 6 and 7 reload the pretrained model first, so "
        "the earlier adaptation never carries over). Supply one zip through the upload dialog on Colab, or a zip or folder "
        "path in `BYOD_PATH` on any runtime. It holds a `records.jsonl` (or `records.json`) of `{id, image, captions}` "
        "objects — `image` a path relative to the records file (sub-folders such as `photos/img_001.jpg` are kept), "
        "`captions` one or more reference captions, optional `image_id` and `category` — beside the image files. It needs "
        "at least **12 records on 12 different images**, because the split by image must leave at least 8 training, 2 "
        "validation and 2 test records; Section 4 checks this before any model runs and names the split it refuses. A new "
        "upload replaces the previous one. The data passes through the same validation, seeded image-disjoint split, "
        "baselines, fine-tuning, held-out evaluation, artifact export and reload-parity cells as the VizWiz sample. The "
        "expected schema and the ceilings are stated in the Prerequisites and in Section 4, and uploaded files stay inside "
        "this runtime. BYOD is optional and never part of the default path."
    ),
    "pipeline_class": "BlipCaptioningPipeline",
    "weights_key": "blip-image-captioning-base",
    "modules": ["pipeline.py", "metrics.py", "samples.py"],
    "entry_module": "pipeline.py",
    "runtime_imports": ["torch", "transformers"],
    "title": "BLIP image-captioning-base — DIMER E2E image-captioning fine-tuning tutorial (standalone)",
    "badges": [
        (
            "GitHub",
            "https://img.shields.io/badge/GitHub-181717?style=flat&logo=github&logoColor=white",
            "https://github.com/kurtvalcorza/blip-captioning-pipeline",
        ),
        (
            "Open In Colab",
            "https://colab.research.google.com/assets/colab-badge.svg",
            "https://colab.research.google.com/github/kurtvalcorza/blip-captioning-pipeline/blob/main/tutorials/blip_captioning_colab.ipynb",
        ),
        (
            "Hugging Face",
            "https://img.shields.io/badge/%F0%9F%A4%97%20Hugging%20Face-Salesforce%2Fblip--image--captioning--base-ffcc4d?style=flat",
            "https://huggingface.co/Salesforce/blip-image-captioning-base",
        ),
        (
            "Upstream",
            "https://img.shields.io/badge/Upstream-salesforce%2FBLIP-181717?style=flat&logo=github&logoColor=white",
            "https://github.com/salesforce/BLIP",
        ),
        ("arXiv", "https://img.shields.io/badge/arXiv-2201.12086-b31b1b.svg", "https://arxiv.org/abs/2201.12086"),
    ],
    "capability": "image captioning and bounded supervised fine-tuning of the caption decoder's last blocks on a photograph/reference-captions dataset, using the pinned `Salesforce/blip-image-captioning-base` weights",
    "intro": (
        "`Salesforce/blip-image-captioning-base` is the BLIP model of Li et al. (2022) — a ViT-B/16 image encoder at 384×384 "
        "and a 12-layer BERT-style caption decoder that cross-attends to the image features; 223,971,644 parameters "
        "(the Hub's *247M* counts the decoder's tied output projection twice), pretrained on 129 M image–text pairs and "
        "fine-tuned on COCO Captions — published under the **BSD-3-Clause** licence. At inference it encodes the resized "
        "image and generates a sentence token by token with greedy decoding under a caller-owned `max_new_tokens` budget, from "
        "scratch or continuing a prefix you supply. **No score exists**: the caption is generated text with no probability and "
        "no correctness signal, and a fluent caption is **not evidence that it describes the image**.\n\n"
        "What this notebook adds to inference is **adaptation with reference captions**. The dataset is real and out of the "
        "model's distribution: VizWiz-Captions (Gurari et al., ECCV 2020; **CC BY 4.0**) — photographs taken by blind people, "
        "each with up to five crowd-written captions in a style COCO does not have (what is being held, what a label says, "
        "that the picture is blurry or badly framed) — a population the model never saw and a convention it does not know. The "
        "notebook reads only the four text columns of one pinned Hub shard (about 0.5 MB over HTTPS range requests) and the "
        "image column of its **first row group** (336 photographs in one 84 MB range read, each pinned by size and SHA-256 in "
        "the carried module). The frozen model is already a competent captioner — the recorded runs of the previous notebook "
        "version measured CIDEr-D about 0.59 on the test photographs against 0.05 for the best constant caption — so the honest "
        "question is a narrow one: does a bounded adaptation of the caption decoder's last blocks on 208 photographs move the "
        "consensus metric on an image-disjoint test split, and which of the four metrics move with it? Three captioning "
        "metrics are implemented in pure Python in the carried modules (**BLEU-4**, **ROUGE-L**, **CIDEr-D** — own "
        "implementations of the `coco-caption` definitions, with CIDEr-D's document frequencies taken from the evaluated set) "
        "beside the plumbing check `unigram_f1`, and two **non-neural baselines** — the corpus-medoid constant caption and a "
        "colour nearest neighbour — show where a system with no model sits. Nothing here is a quality claim about your "
        "photographs: it is one seeded split of one corpus.\n\n"
        "**Weight-format note:** upstream hosts no SafeTensors at the pinned revision; the carried module executes the "
        "digest-pinned `pytorch_model.bin` (a pickle, deserialised with `weights_only=True` after its SHA-256 is checked), "
        "while the `tf_model.h5` upstream also hosts is DIMER's upload artifact and is never loaded here. Section 3 stages "
        "and digest-verifies the snapshot before the processor or the model is constructed.\n\n"
        "**Who this is for.** A learner who knows basic Python and has met the idea of an image model, and wants to see how a "
        "pretrained captioner is measured against reference captions and adapted to a new kind of photograph. No prior "
        "experience with BLIP, captioning metrics or fine-tuning is assumed; each term is explained where it is first used and "
        "again in the **Glossary** at the end.\n\n"
        "**Input → Model → Output.**\n\n"
        "| | Captioning | Fine-tuning |\n"
        "|---|---|---|\n"
        "| Input | one image (any size from 16 to 4096 px a side), an optional prefix and a token budget | 208 training photographs, each with up to five reference captions |\n"
        "| Model | BLIP: ViT-B/16 image encoder + 12-layer caption decoder, greedy decoding | the same model with the caption decoder's last 2 blocks and head transform trained |\n"
        "| Output | one caption string, its token count and a `truncated` flag — no score | an adapter (safetensors) and held-out BLEU-4 / ROUGE-L / CIDEr-D / unigram F1 |\n\n"
        "**How to use this notebook.** Choose a runtime (a GPU runtime is faster; CPU works), then **Runtime → Run all**. "
        "Sections 1–3 are **infrastructure** — the isolated environment, the carried code and the model verification — and "
        "can be run without study. The learning path starts in Section 4. Form fields (`# @param`) are the only values meant "
        "to be edited; the defaults reproduce the recorded path. Each stage states what it does and asks you to **predict** "
        "before it runs, and the next cell opens with **What to notice** and a collapsible **Check your reasoning** block with "
        "a worked answer. Each optional experiment names the cell to change and the cells to re-run. Section 10 is a "
        "**change-one-thing activity**. **Troubleshooting**, a **Glossary** and a **Conclusion** template are at the end. Your "
        "notes are optional and are not required submissions.\n\n"
        "**Roadmap:** 4 fetch, validate and split the photographs → 5 caption drawn scenes with the pretrained model → 6 two "
        "baselines and the pretrained model's score on the test photographs → 7 fine-tune the caption decoder's last blocks → "
        "8 compare on the held-out photographs → 9 re-caption, export and reload → 10 **change one thing: a higher learning "
        "rate** → conclude."
    ),
    "learning_objectives": (
        "by the end you should be able to (1) explain *image → encoder and caption decoder → one generated sentence* and say "
        "why a caption carries no score (Section 5); (2) read BLEU-4, ROUGE-L and CIDEr-D against several reference captions "
        "and say why the frozen model sits far above a constant caption (Section 6); (3) explain how validation, never test, "
        "chooses the kept epoch, and why choosing the default hyperparameters by their test score makes the test gain "
        "optimistic (Sections 7–8); (4) predict and then check which metrics move after a bounded fine-tuning, and on which "
        "category of photograph (Section 8); (5) predict and then observe what a higher learning rate does to validation "
        "CIDEr-D and to the epoch the selector keeps (Section 10); and (6) check that an exported adapter reproduces the "
        "evaluated model (reload parity, Section 9)."
    ),
    "exclusions": (
        "reading text in the image (BLIP is not an OCR model, even though VizWiz captions often transcribe labels), visual "
        "question answering (a separate checkpoint), dense or region captioning (one sentence per image, no localisation), "
        "captions in languages other than English, batch throughput, sampling, beam search or repetition penalties (the "
        "upstream evaluation used beam search; this notebook decodes greedily for reproducibility), SPICE (needs a scene-graph "
        "parser), evaluation on the COCO or VizWiz benchmarks proper (only one seeded 318-photograph sample is scored here), "
        "fine-tuning of the vision encoder, the embeddings or the tied output projection, training on images that are not the "
        "pinned sample or your own uploads, and any claim that a VizWiz split stands in for your photographs. The repository "
        "exposes none of these."
    ),
    "prerequisites": [
        "- **Learner:** basic Python and Colab or Jupyter familiarity; no prior experience with BLIP, captioning metrics or fine-tuning. The notebook explains greedy decoding, reference captions, BLEU-4 (n-gram precision with a brevity penalty), ROUGE-L (longest-common-subsequence F-measure), CIDEr-D (TF-IDF-weighted n-gram consensus), validation-based epoch selection and why a pickle checkpoint needs a digest check before `torch.load` where they are first used; the Glossary repeats them.",
        "- **Runtime:** a fresh **Linux x86_64** runtime — Google Colab, Kaggle or Linux Jupyter. Section 1 builds its own Python 3.12.12 environment from a hash-locked list of manylinux wheels, so the kernel's own Python version does not matter, and a Windows or macOS kernel is not supported (Section 1 stops with that message). The default path runs on CPU (float32) and uses CUDA automatically when available. The locked install (PyTorch 2.14.0 with its CUDA libraries) and the 990 MB checkpoint are the large downloads; the row group of photographs adds about 84 MB. Measured on the previous notebook version, whose model stages are the same, in a local Windows CPU pre-flight (2026-09-19, float32, files pre-staged): about 32 s to caption the 70 test photographs and 487 s for the four epochs of fine-tuning over 889 image–caption pairs with a 40-photograph validation pass per epoch; the whole default path took 879 s. The Kaggle Tesla T4 run of the same version took 439 s including the downloads. No hosted CPU run is recorded; expect roughly the CPU pre-flight figures there (an estimate).",
        "- **Data contract:** records are `{id, image, captions}` — an image file decodable by Pillow with sides between `MIN_IMAGE_SIDE` (16) and `MAX_IMAGE_SIDE` (4096) px and one or more non-empty reference captions of at most `MAX_CAPTION_CHARS` (500) characters (`MIN_CAPTIONS` = 1; VizWiz supplies up to five); optional `image_id` (defaults to the id) groups records on the same image and optional `category` labels the breakdown (`text` / `no-text` in the sample, from the corpus's text-detected flag). Ids match `[A-Za-z0-9_.:-]{1,64}` and are unique; a dataset holds at most 5,000 records; every record on the same image lands in the same split so a test image is never trained on; every (image, reference caption) pair is one training sample. The seeded split keeps about 20 % of the images for test and 15 % for validation and must leave at least 8 training, 2 validation and 2 test records, so a BYOD dataset needs at least **12 records on 12 different images** (more if several records share an image). Section 4 checks this before any model runs and names the split it refuses.",
        "- **BYOD layout:** one zip (by upload, or by path in `BYOD_PATH`; a folder path also works) holding exactly one `records.jsonl` or `records.json` and the images, with each `image` given relative to the records file — sub-folders are kept as written. The zip may hold at most 20,000 members and expand to at most 2 GB; links and members that would land outside the upload folder are refused before anything is written. A new upload replaces the files of the previous one.",
        "- **Validation is structural, not semantic:** every image is opened and decoded and every caption checked, but nothing checks that a reference caption is right — a mislabelled corpus is fine-tuned on without complaint.",
        "- **Privacy:** Do not upload confidential or restricted data to a hosted runtime unless you are authorized to process it there — photographs of people, documents or homes are exactly that. The default path uploads nothing.",
        "- **External access (data):** besides the model snapshot, the default path reads two parts of one object in the Hub dataset repository `mm-eval/VizWiz-Captions` at the immutable revision `c4a6d897…` (`data/val-00004-of-00005.parquet`, 392,245,504 bytes, SHA-256 `4492465a…`): the declared size and SHA-256 are checked against the pins before any byte is read; the four text columns of all 1,550 rows are fetched over HTTPS range requests through `pyarrow` (only the parquet footer and those column chunks) and refused unless their decoded SHA-256 matches; then the image column of row group 0 only (336 JPEG files, about 84 MB) is read the same way, each photograph pinned by size and SHA-256 in the carried module and refused on any mismatch. The corpus is CC BY 4.0 (Gurari et al., 2020).",
    ],
    "cells": [
        {
            "md": (
                "## 4. VizWiz photographs, captions and split\n\n"
                "`fetch_annotations` reads the pinned shard's four text columns (or the cache under `weights/vizwiz-captions/`): "
                "it first checks the byte size and SHA-256 the Hub declares for the file against the pins, then reads only the "
                "parquet footer and those column chunks through `pyarrow` over HTTPS range requests, and refuses the decoded "
                "columns unless their SHA-256 matches. `fetch_images` stages the 336 pinned photographs of row group 0 — each "
                "cached file is re-hashed; anything missing is read from the shard's image column in one range read and refused "
                "on any size or SHA-256 mismatch. `build_sample_dataset` keeps the 318 photographs that carry at least one "
                "reference caption (the Hub re-conversion dropped rejected and pre-canned captions), shuffles them with "
                "`SPLIT_SEED` and cuts them **by image** into 208 / 40 / 70 training, validation and test records, each "
                "labelled `text` or `no-text` from the corpus's text-detected flag. `validate_dataset` then opens and decodes "
                "every image and checks every record against the contract, `check_split_disjoint` asserts no image is shared, "
                "and the training split is written to `outputs/{stem}_train.jsonl` in the shape BYOD expects.\n\n"
                "**Bring your own data:** set `USE_BYOD = True`, either leave `BYOD_PATH` empty to get an upload dialog "
                "(Colab only) or set it to a zip or folder already in this runtime, then select this cell and choose **Runtime → "
                "Run after**. The cell empties `work/byod/` first, so a second upload never reads the first one's files; it "
                "refuses a zip with more than 20,000 members, more than 2 GB expanded, a link or a member that would land outside "
                "`work/byod/`, before writing anything; it keeps sub-folders, so `image` paths are read relative to the records "
                "file; and an empty or cancelled upload, or a zip without `records.jsonl` / `records.json`, stops with a message "
                "saying what to supply. `split_dataset` then makes a seeded 65 / 15 / 20 % split **by image** and refuses a "
                "dataset that leaves fewer than 8 training, 2 validation or 2 test records, naming the split (at least 12 "
                "records on 12 different images). Under BYOD the printed provenance and `result.json` describe your upload, "
                "not the VizWiz corpus.\n\n"
                "Look for: 1,550 annotation rows, 336 photographs, three digests, the category mix per split, captions per image "
                "between 1 and 5, and four refusal probes — a duplicate id, a missing image file, an empty caption list and a "
                "dataset too small to split — each rejected before `torch` does anything.\n\n"
                "**Predict before running:** a little over half of the photographs contain text (labels, screens, packaging). "
                "Will the 70 test photographs have the same mix as the 208 training ones, exactly or only roughly?"
            ),
            "code": (
                "import collections\n"
                "import hashlib\n"
                "import io\n"
                "import json\n"
                "import shutil\n"
                "import stat\n"
                "import zipfile\n\n"
                "USE_BYOD = False  # @param {{type:\"boolean\"}}\n"
                "BYOD_PATH = ''  # @param {{type:\"string\"}}\n"
                "SPLIT_SEED = 42  # @param {{type:\"integer\"}}\n\n"
                "MAX_ZIP_MEMBERS = 20_000\n"
                "MAX_ZIP_BYTES = 2_000_000_000\n"
                "RECORDS_NAMES = ('records.jsonl', 'records.json')\n\n\n"
                "def extract_zip(payload, root, label):\n"
                "    \"\"\"Extract an uploaded zip under root, keeping sub-folders and refusing the whole archive before writing anything unsafe.\"\"\"\n"
                "    base = root.resolve()\n"
                "    try:\n"
                "        archive = zipfile.ZipFile(io.BytesIO(payload))\n"
                "    except zipfile.BadZipFile:\n"
                "        raise ValueError(f'{{label}} is not a readable zip file: zip the records file and the images together and supply that zip.') from None\n"
                "    with archive:\n"
                "        members = archive.infolist()\n"
                "        expanded = sum(m.file_size for m in members)\n"
                "        if len(members) > MAX_ZIP_MEMBERS or expanded > MAX_ZIP_BYTES:\n"
                "            raise ValueError(f'{{label}} holds {{len(members)}} members and expands to {{expanded}} bytes; the limits are {{MAX_ZIP_MEMBERS}} members and {{MAX_ZIP_BYTES}} bytes, checked before anything is written.')\n"
                "        for member in members:\n"
                "            if stat.S_ISLNK(member.external_attr >> 16):\n"
                "                raise ValueError(f'{{label}}: zip member {{member.filename!r}} is a symbolic link, which is not accepted; nothing was extracted.')\n"
                "            target = (root / member.filename).resolve()\n"
                "            if target == base or not target.is_relative_to(base):\n"
                "                raise ValueError(f'{{label}}: zip member {{member.filename!r}} would land outside the upload folder; nothing was extracted.')\n"
                "        for member in members:\n"
                "            if not member.is_dir():\n"
                "                target = (root / member.filename).resolve()\n"
                "                target.parent.mkdir(parents=True, exist_ok=True)\n"
                "                target.write_bytes(archive.read(member))\n\n\n"
                "def find_records_file(root, label):\n"
                "    found = sorted(p for p in Path(root).rglob('*') if p.name in RECORDS_NAMES and '__MACOSX' not in p.parts)\n"
                "    if not found:\n"
                "        raise ValueError(f'No records.jsonl or records.json found in {{label}}. Put one records file of {{{{id, image, captions}}}} objects beside the images (image paths relative to it), then run this cell again.')\n"
                "    if len(found) > 1:\n"
                "        raise ValueError(f'{{label}} holds more than one records file; keep exactly one of: ' + ', '.join(str(p.relative_to(root)) for p in found))\n"
                "    return found[0]\n\n\n"
                "os.makedirs('outputs', exist_ok=True)\n"
                "byod = None\n"
                "if USE_BYOD:\n"
                "    byod_root = Path('work') / 'byod'\n"
                "    if byod_root.exists():\n"
                "        shutil.rmtree(byod_root)  # a new upload never reads files left by an earlier one\n"
                "    byod_root.mkdir(parents=True)\n"
                "    payload = None\n"
                "    if BYOD_PATH.strip():\n"
                "        source = Path(BYOD_PATH.strip()).expanduser()\n"
                "        if not source.exists():\n"
                "            raise FileNotFoundError(f'BYOD_PATH = {{BYOD_PATH!r}} does not exist in this runtime: fix the path, or leave BYOD_PATH empty to upload a zip in Colab.')\n"
                "        file_name = source.name\n"
                "        if source.is_dir():\n"
                "            records_file = find_records_file(source, str(source))\n"
                "        elif source.suffix.lower() == '.zip':\n"
                "            payload = source.read_bytes()\n"
                "            extract_zip(payload, byod_root, file_name)\n"
                "            records_file = find_records_file(byod_root, file_name)\n"
                "        else:\n"
                "            raise ValueError(f'BYOD_PATH must name a .zip or a folder holding records.jsonl / records.json and the images, not {{file_name!r}}.')\n"
                "    else:\n"
                "        try:\n"
                "            from google.colab import files\n"
                "        except ImportError:\n"
                "            raise RuntimeError('The upload dialog needs Google Colab. Elsewhere, put the zip (or folder) in this runtime and set BYOD_PATH to its path.') from None\n"
                "        uploaded = files.upload()\n"
                "        if len(uploaded) != 1:\n"
                "            raise RuntimeError(f'Upload exactly one .zip file (received {{len(uploaded)}}). Run this cell again and choose a file, or set BYOD_PATH to a zip or folder already in this runtime.')\n"
                "        file_name, payload = next(iter(uploaded.items()))\n"
                "        if not file_name.lower().endswith('.zip'):\n"
                "            raise ValueError(f'Upload a .zip holding records.jsonl / records.json and the images, not {{file_name!r}}.')\n"
                "        extract_zip(payload, byod_root, file_name)\n"
                "        records_file = find_records_file(byod_root, file_name)\n"
                "    records = load_byod_dataset(records_file)\n"
                "    splits = split_dataset(records, seed=SPLIT_SEED, base_dir=records_file.parent)\n"
                "    data_source = 'BYOD (' + file_name + ')'\n"
                "    raw_rows = {{'byod': len(records)}}\n"
                "    byod = {{'file': file_name, 'records_file': records_file.name, 'records': len(records), 'zip_sha256': hashlib.sha256(payload).hexdigest() if payload is not None else None, 'minimum_records': byod_minimum_records()}}\n"
                "else:\n"
                "    annotations = fetch_annotations(cache_dir='weights/vizwiz-captions')\n"
                "    image_paths = fetch_images(sorted(IMAGE_PINS), cache_dir='weights/vizwiz-captions')\n"
                "    raw_rows = {{'annotations': len(annotations), 'photographs': len(image_paths), 'captioned': sum(1 for r in annotations if r['id'] in IMAGE_PINS and r['captions'])}}\n"
                "    splits = build_sample_dataset(annotations, seed=SPLIT_SEED, image_paths=image_paths)\n"
                "    data_source = f'{{CORPUS_NAME}} {{CORPUS_RELEASE}} ({{CORPUS_LICENSE}})'\n"
                "dataset_manifests = {{name: validate_dataset(part, min_records=MIN_RECORDS if name == 'train' else 1) for name, part in splits.items()}}\n"
                "splits = {{name: manifest['records'] for name, manifest in dataset_manifests.items()}}\n"
                "disjoint = check_split_disjoint(splits)\n"
                "train_records, val_records, test_records = splits['train'], splits['validation'], splits['test']\n"
                "categories = {{name: manifest['categories'] for name, manifest in dataset_manifests.items()}}\n"
                "write_dataset_jsonl(splits['train'], 'outputs/{stem}_train.jsonl')\n"
                "if USE_BYOD:\n"
                "    print({{'data_source': data_source, 'raw_rows': raw_rows, 'splits': disjoint, 'byod': byod}})\n"
                "else:\n"
                "    print({{'data_source': data_source, 'raw_rows': raw_rows, 'splits': disjoint, 'text_sha256': CORPUS_FILE['text_sha256'][:16] + '...', 'pinned_photographs': len(IMAGE_PINS)}})\n"
                "for name, manifest in dataset_manifests.items():\n"
                "    print({{name: {{'n': manifest['n_records'], 'unique_images': manifest['unique_images'], 'categories': manifest['categories'], 'captions_per_image': manifest['captions_per_image'], 'caption_words': manifest['caption_words'], 'digest': manifest['digest'][:16] + '...'}}}})\n"
                "example = splits['train'][0]\n"
                "print({{'example': {{'id': example['id'], 'image': Path(example['image']).name, 'size': example['image_size'], 'category': example['category'], 'captions': example['captions']}}}})\n\n"
                "probes = {{\n"
                "    'duplicate id': [{{**r, 'id': 'same'}} for r in splits['train'][:8]],\n"
                "    'missing image file': [{{**splits['train'][0], 'image': 'work/does-not-exist.jpg'}}, *splits['train'][1:8]],\n"
                "    'empty caption list': [{{**splits['train'][0], 'captions': []}}, *splits['train'][1:8]],\n"
                "    'too small': splits['train'][:3],\n"
                "}}\n"
                "for name, probe in probes.items():\n"
                "    try:\n"
                "        validate_dataset(probe)\n"
                "        print({{'probe': name, 'verdict': 'accepted'}})\n"
                "    except (TypeError, ValueError) as exc:\n"
                "        print({{'probe': name, 'rejected': str(exc)[:110]}})"
            ),
        },
        {
            "md": (
                "**What to notice:** the three split sizes, the category counts per split, and that the splits share no image.\n\n"
                "<details><summary>Check your reasoning</summary>Only roughly. The split shuffles whole images with a seed and "
                "cuts the list by count; it does not stratify by category. In the recorded runs of the previous notebook version "
                "(same seed) `text` held 110 of 208 training photographs (53 %), 25 of 40 validation and 40 of 70 test (57 %). That "
                "is close enough to read the per-category scores later, but the validation split, with 40 photographs, is small "
                "and noisy — which matters for the epoch it picks in Section 7.</details>\n\n"
                "## 5. Caption through the inference contract\n\n"
                "The inference contract is exercised as the inference-only tutorial exercised it: three flat cartoon scenes — "
                "a red house with a tree, a beach with a red sailboat, an apple and an orange on a table — are drawn in code "
                "with Pillow (no text rendering, so their digests are stable across builds), a different image family from the "
                "photographs, and scenes the model will be asked to caption again after adaptation. `validate_inputs` applies "
                "exactly the checks `caption` applies (image sides `MIN_IMAGE_SIDE`..`MAX_IMAGE_SIDE`, an optional prefix up to "
                "`MAX_PREFIX_CHARS`, `max_new_tokens` in `[1, MAX_NEW_TOKENS]`) and returns an input manifest; a 4-pixel image "
                "is validated too and its rejection recorded as a finding. `caption` returns the decoded text, the checked "
                "prefix, `image_size`, `new_tokens`, a `truncated` flag and the model identity. **No score exists**: the "
                "caption is generated text with no probability and no correctness signal — a fluent caption is **not evidence "
                "that it describes the image**, and greedy decoding (always taking the most likely next token) is a "
                "reproducibility property, not a quality one. The cell records which expected keywords appear in each caption — "
                "an observation, not a metric; whether captions are *right* is what Section 6 measures on the test photographs "
                "with several human references each.\n\n"
                "**Every pass starts from the pretrained model.** Section 7 changes the model in memory. If this cell, Section 6 "
                "or Section 7 runs again after Section 7 (a BYOD run or one of the optional experiments), it first reloads the "
                "pretrained model from the verified snapshot with `reset_to_pretrained()`, so a *before* or *frozen* number is "
                "never read from the adapted model.\n\n"
                "**Predict before running:** the fruit drawing shows a red apple and an orange. Will the caption name both fruits?"
            ),
            "code": (
                "import gc\n"
                "import time\n\n"
                "import numpy as np\n"
                "from PIL import Image, ImageDraw\n\n"
                "CAPTION_MAX_TOKENS = 30  # @param {{type:\"integer\"}}\n\n\n"
                "def reset_to_pretrained():\n"
                "    \"\"\"Sections 5-7 start from the pretrained model: if an earlier pass adapted `pipe`, reload it from the verified snapshot.\"\"\"\n"
                "    global pipe\n"
                "    if pipe.adapter is None:\n"
                "        return\n"
                "    pipe = None\n"
                "    gc.collect()\n"
                "    if torch.cuda.is_available():\n"
                "        torch.cuda.empty_cache()\n"
                "    pipe = BlipCaptioningPipeline.from_pretrained(weights_dir=WEIGHTS_DIR)\n"
                "    print({{'reloaded': 'the pretrained model, from the verified snapshot', 'reason': 'an earlier pass had adapted the model in memory'}})\n\n\n"
                "def synthetic_scenes():\n"
                "    \"\"\"Three flat cartoon scenes drawn with Pillow (no text); returns [(name, image, expected keywords)].\"\"\"\n"
                "    house = Image.new('RGB', (640, 480), (135, 206, 235))  # sky\n"
                "    d = ImageDraw.Draw(house)\n"
                "    d.rectangle([0, 300, 640, 480], fill=(60, 179, 75))  # grass\n"
                "    d.ellipse([500, 40, 600, 140], fill=(255, 215, 0))  # sun\n"
                "    d.rectangle([120, 180, 320, 330], fill=(200, 40, 40))  # red house\n"
                "    d.polygon([(100, 180), (220, 90), (340, 180)], fill=(90, 50, 20))  # brown roof\n"
                "    d.rectangle([200, 260, 240, 330], fill=(70, 40, 20))  # brown door\n"
                "    d.ellipse([420, 260, 520, 360], fill=(40, 100, 40))  # tree crown\n"
                "    d.rectangle([460, 350, 480, 420], fill=(90, 60, 30))  # trunk\n"
                "    d.ellipse([60, 380, 140, 440], fill=(255, 255, 255))  # white ball\n"
                "    beach = Image.new('RGB', (640, 480), (120, 190, 240))  # sky\n"
                "    d = ImageDraw.Draw(beach)\n"
                "    d.rectangle([0, 220, 640, 330], fill=(30, 110, 200))  # sea\n"
                "    d.rectangle([0, 330, 640, 480], fill=(238, 214, 150))  # sand\n"
                "    d.ellipse([60, 40, 150, 130], fill=(255, 230, 80))  # sun\n"
                "    d.polygon([(400, 330), (470, 330), (435, 210)], fill=(230, 40, 40))  # red sail\n"
                "    d.rectangle([432, 210, 438, 330], fill=(90, 60, 30))  # mast\n"
                "    d.ellipse([200, 370, 260, 430], fill=(255, 120, 40))  # beach ball\n"
                "    fruit = Image.new('RGB', (480, 480), (250, 250, 245))\n"
                "    d = ImageDraw.Draw(fruit)\n"
                "    d.ellipse([60, 120, 220, 280], fill=(220, 30, 30))  # red apple\n"
                "    d.rectangle([135, 95, 145, 125], fill=(80, 50, 20))  # stalk\n"
                "    d.ellipse([250, 140, 430, 300], fill=(255, 170, 20))  # orange\n"
                "    d.polygon([(90, 400), (400, 400), (360, 330), (130, 330)], fill=(180, 120, 60))  # table\n"
                "    return [\n"
                "        ('synthetic_house_640x480.png', house, ['house', 'tree', 'red']),\n"
                "        ('synthetic_beach_640x480.png', beach, ['beach', 'sail', 'sun']),\n"
                "        ('synthetic_fruit_480x480.png', fruit, ['apple', 'orange']),\n"
                "    ]\n\n\n"
                "reset_to_pretrained()\n"
                "scenes = synthetic_scenes()\n"
                "scene_names = [name for name, _, _ in scenes]\n"
                "scene_images = [image for _, image, _ in scenes]\n"
                "expected_keywords = [keywords for _, _, keywords in scenes]\n"
                "scene_digests = {{name: hashlib.sha256(np.asarray(image.convert('RGB')).tobytes()).hexdigest() for name, image in zip(scene_names, scene_images)}}\n"
                "ceilings = {{'MIN_IMAGE_SIDE': MIN_IMAGE_SIDE, 'MAX_IMAGE_SIDE': MAX_IMAGE_SIDE, 'IMAGE_SIZE': IMAGE_SIZE, 'MAX_PREFIX_CHARS': MAX_PREFIX_CHARS, 'MAX_NEW_TOKENS': MAX_NEW_TOKENS, 'DEFAULT_MAX_NEW_TOKENS': DEFAULT_MAX_NEW_TOKENS, 'DECODING': DECODING, 'MIN_RECORDS': MIN_RECORDS, 'MAX_RECORDS': MAX_RECORDS, 'MIN_CAPTIONS': MIN_CAPTIONS, 'MAX_CAPTION_CHARS': MAX_CAPTION_CHARS}}\n"
                "print(ceilings)\n"
                "input_manifest = validate_inputs(scene_images, max_new_tokens=CAPTION_MAX_TOKENS, names=scene_names)\n"
                "try:\n"
                "    validate_inputs([Image.new('RGB', (4, 4))])\n"
                "except ValueError as exc:\n"
                "    input_manifest['findings'].append({{'input': 'tiny-image-probe', 'verdict': 'rejected', 'message': str(exc)}})\n"
                "with open('outputs/{stem}_input_manifest.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump(input_manifest, handle, indent=2, ensure_ascii=False)\n"
                "print({{'scenes': scene_names, 'rgb_sha256': {{k: v[:16] + '...' for k, v in scene_digests.items()}}, 'manifest_verdict': input_manifest['verdict'], 'findings': len(input_manifest['findings'])}})\n"
                "results = []\n"
                "for name, image, keywords in scenes:\n"
                "    started = time.perf_counter()\n"
                "    result = pipe.caption(image, max_new_tokens=CAPTION_MAX_TOKENS)\n"
                "    result['image'] = name\n"
                "    result['keyword_hits'] = keyword_hits(result['caption'], keywords)\n"
                "    results.append({{'seconds': round(time.perf_counter() - started, 3), **result}})\n"
                "    print(f\"{{name}}\\n   caption: {{result['caption']!r}}  ({{result['new_tokens']}} tokens{{', TRUNCATED' if result['truncated'] else ''}})\\n   keywords: {{result['keyword_hits']}}\")\n"
                "checks = {{\n"
                "    'one_result_per_image': len(results) == len(scenes),\n"
                "    'captions_are_text': all(isinstance(r['caption'], str) and r['caption'] for r in results),\n"
                "    'budget_respected': all(r['new_tokens'] <= CAPTION_MAX_TOKENS for r in results),\n"
                "    'setting_echoed': all(r['generation']['max_new_tokens'] == CAPTION_MAX_TOKENS and r['generation']['do_sample'] is False for r in results),\n"
                "}}\n"
                "if not all(checks.values()):\n"
                "    raise RuntimeError(f'caption output failed a sanity check: {{checks}}')\n"
                "frozen_scene = evaluation_report(results, None, sample_kind='synthetic')\n"
                "print({{'checks': checks, 'frozen_scene_verdict': frozen_scene['verdict'], 'any_truncated': any(r['truncated'] for r in results)}})"
            ),
        },
        {
            "md": (
                "**What to notice:** each caption's keyword hits, and that nothing in the output says how sure the model is.\n\n"
                "<details><summary>Check your reasoning</summary>Probably not. In the recorded runs of the previous notebook "
                "version, and in the model card's CPU smoke, the pretrained model captioned the drawings `a red house with a tree "
                "and a ball`, `a beach scene with a sail and a sun` and `a red and yellow apple on a white background`: the orange "
                "became part of a second apple. The sentence is fluent and confident, and nothing in the output warns you — a "
                "caption has no score. These are flat cartoons, not the photographs the model was trained on, so three drawings "
                "are an observation about the contract, not a measurement of quality.</details>\n\n"
                "## 6. Baselines and the frozen model's score on the test photographs\n\n"
                "Three systems frame the adaptation, each read four ways. The **constant-caption baseline** answers every "
                "photograph with the one training caption that scores highest against all other training references — the "
                "corpus medoid, a sentence that is safe everywhere and right nowhere. The **colour-nearest-neighbour "
                "baseline** answers with the first reference caption of the training photograph whose 3×3 mean-colour grid is "
                "closest — a lookup that knows the image through 27 numbers. The **frozen model** captions the test "
                "photographs with the budget from Section 5 and is scored with the same metrics: **BLEU-4** (corpus-level "
                "clipped n-gram precision with a brevity penalty), **ROUGE-L** (longest-common-subsequence F-measure against the "
                "best reference), **CIDEr-D** (TF-IDF-weighted n-gram consensus over all references, the metric captioning "
                "leaderboards are ranked by) and the plumbing check **unigram F1**, all after lower-casing and punctuation "
                "removal. The cell reloads the pretrained model first if an earlier pass adapted it, and refuses to report an "
                "adapted model as frozen. It prints whether the frozen model beats the constant caption instead of asserting it: "
                "on your own photographs it may not, and that is a result to read. Captioning the 70 test photographs took about "
                "32 s in the local CPU pre-flight of the previous notebook version.\n\n"
                "**Predict before running:** where will the frozen model's CIDEr-D land relative to the two baselines? And which "
                "category, `text` or `no-text`, will it caption better?"
            ),
            "code": (
                "reset_to_pretrained()\n"
                "baseline_constant = constant_caption_baseline(train_records, test_records)\n"
                "baseline_neighbour = colour_neighbour_baseline(train_records, test_records)\n"
                "METRICS = ('bleu4', 'rouge_l', 'cider_d', 'unigram_f1')\n"
                "print({{'constant_caption_baseline': {{k: round(baseline_constant[k], 3) for k in METRICS}}, 'n': baseline_constant['n'], 'caption': baseline_constant['baseline']}})\n"
                "print({{'colour_neighbour_baseline': {{k: round(baseline_neighbour[k], 3) for k in METRICS}}, 'note': baseline_neighbour['baseline']}})\n"
                "t0 = time.perf_counter()\n"
                "frozen_test = pipe.evaluate(test_records, max_new_tokens=CAPTION_MAX_TOKENS)\n"
                "if frozen_test['adapted']:\n"
                "    raise RuntimeError('Section 6 must score the pretrained model, but the model in memory is adapted. Restart the session and choose Run all.')\n"
                "print({{'frozen_model_test': {{k: round(frozen_test[k], 3) for k in METRICS}}, 'mean_words': round(frozen_test['mean_words'], 1), 'n': frozen_test['n'], 'verdict': frozen_test['verdict'], 'adapted': frozen_test['adapted'], 'seconds': round(time.perf_counter() - t0, 1)}})\n"
                "print({{'frozen_above_constant_caption': frozen_test['cider_d'] > baseline_constant['cider_d']}})\n"
                "print({{'definitions': frozen_test['definitions']}})\n\n\n"
                "def model_caption(pipeline):\n"
                "    def predict(record):\n"
                "        with Image.open(record['image']) as photo:\n"
                "            photo.load()\n"
                "            return pipeline.caption(photo, max_new_tokens=CAPTION_MAX_TOKENS)['caption']\n"
                "    return predict\n\n\n"
                "def by_category(predict, records):\n"
                "    \"\"\"CIDEr-D per category, with document frequencies from the whole evaluated set (as in `evaluate`).\"\"\"\n"
                "    scores = cider_d([predict(r) for r in records], [reference_captions(r) for r in records])\n"
                "    groups = collections.defaultdict(list)\n"
                "    for record, score in zip(records, scores, strict=True):\n"
                "        groups[record['category']].append(score)\n"
                "    return {{category: {{'n': len(values), 'cider_d': round(sum(values) / len(values), 3)}} for category, values in sorted(groups.items())}}\n\n\n"
                "medoid = medoid_caption(train_records)\n"
                "constant_fields = by_category(lambda record: medoid, test_records)\n"
                "frozen_predictions = {{r['id']: model_caption(pipe)(r) for r in test_records}}\n"
                "frozen_fields = by_category(lambda record: frozen_predictions[record['id']], test_records)\n"
                "print({{'by_category': {{'constant': constant_fields, 'frozen': frozen_fields}}}})\n"
                "for record in test_records[:3]:\n"
                "    print({{'category': record['category'], 'frozen': frozen_predictions[record['id']], 'references': reference_captions(record)[:2]}})"
            ),
        },
        {
            "md": (
                "**What to notice:** the gap between the two baselines and the frozen model, `adapted: False`, and the "
                "per-category line.\n\n"
                "<details><summary>Check your reasoning</summary>Far above both. In the recorded runs of the previous notebook "
                "version the constant caption scored CIDEr-D 0.052 and the colour neighbour 0.042, while the frozen model scored "
                "0.590 (BLEU-4 0.213): a trained captioner names the objects in the photograph, which no fixed sentence and no "
                "colour lookup can do. Perhaps surprisingly, the `text` photographs scored higher (0.638) than the `no-text` ones "
                "(0.525) — not because the model reads the labels (it does not), but because packaged products and screens are "
                "objects COCO-trained captioners name well, while the `no-text` photographs are often blurry or badly framed. "
                "CIDEr-D can exceed 1 and is not a percentage: it weights the n-grams the references agree on.</details>\n\n"
                "## 7. Bounded fine-tuning of the caption decoder's last blocks\n\n"
                "`pipe.adapt` trains only the last `TRAINABLE_DECODER_LAYERS` blocks of the caption decoder plus its output "
                "head's transform and bias — two blocks by default, 19,526,204 of 223,971,644 parameters; the vision encoder, "
                "every embedding and the head's projection weight (tied to the word embeddings) stay frozen. The frozen vision "
                "encoder's output is computed **once** per training photograph and reused across epochs, so an epoch costs a "
                "decoder pass per (image, caption) pair — every reference caption is a training sample, the BLIP fine-tuning "
                "convention, 889 pairs per epoch here. The target is decoded from the `[DEC]` start token with the model's own "
                "label-smoothed cross-entropy; AdamW at a fixed learning rate, gradient clipping at 1.0, seeded shuffling and no "
                "scheduler. Epoch 0 records the frozen model's validation metrics; every epoch is scored on the 40 validation "
                "photographs, and the epoch with the highest **validation** CIDEr-D is kept — the test split plays no part in "
                "that choice. Forty photographs make the selection noisy. The four epochs took 487 s in the local CPU "
                "pre-flight of the previous notebook version; much less on a GPU.\n\n"
                "**How the defaults were chosen — read this before Section 8.** Before the notebook was written, a small sweep "
                "on this same sample compared learning rates and epoch counts **by their score on the test photographs** "
                "(the model card records it: 5e-5 overfit within two epochs and the selector kept epoch 0; 2e-5 over twice the "
                "photographs lowered the test CIDEr-D to 0.496; 1e-5 for six epochs peaked at epoch 4). The default — learning "
                "rate 1e-5, four epochs, two blocks — is the configuration that gained there. So although this run never looks at "
                "the test split to choose anything, the default itself was chosen with it, and the Section 8 gain is a "
                "**selected, optimistic** number rather than independent evidence. An independent estimate would need the sweep "
                "repeated on the validation split (or a development split carved from training) and a test split nobody had "
                "looked at.\n\n"
                "**Adaptation always starts from the pretrained model.** If this cell runs again (for example with "
                "`LEARNING_RATE = 5e-5` in Section 10), it first reloads the pretrained model from the verified snapshot, so the "
                "new training never stacks on the previous one, epoch 0 really is the frozen model, and the exported adapter holds "
                "exactly what this run trained; `pipe.adapt` itself refuses a model that is already adapted.\n\n"
                "**Predict before running:** will validation CIDEr-D rise in every epoch? Which epoch will be kept?"
            ),
            "code": (
                "EPOCHS = 4  # @param {{type:\"integer\"}}\n"
                "LEARNING_RATE = 1e-5  # @param {{type:\"number\"}}\n"
                "BATCH_SIZE = 8  # @param {{type:\"integer\"}}\n"
                "TRAINABLE_DECODER_LAYERS = 2  # @param {{type:\"integer\"}}\n\n\n"
                "def report(entry):\n"
                "    row = {{'epoch': entry['epoch'], 'train_loss': None if entry['train_loss'] is None else round(entry['train_loss'], 4)}}\n"
                "    if entry.get('val'):\n"
                "        row.update({{'val_' + k: round(entry['val'][k], 3) for k in METRICS}})\n"
                "        row['val_mean_words'] = round(entry['val']['mean_words'], 1)\n"
                "    if 'note' in entry:\n"
                "        row['note'] = entry['note']\n"
                "    print(row)\n\n\n"
                "reset_to_pretrained()\n"
                "t0 = time.perf_counter()\n"
                "adapt_result = pipe.adapt(train_records, val_records, epochs=EPOCHS, lr=LEARNING_RATE, batch_size=BATCH_SIZE, trainable_decoder_layers=TRAINABLE_DECODER_LAYERS, progress=report)\n"
                "adapt_seconds = round(time.perf_counter() - t0, 1)\n"
                "print({{'trainable_parameters': adapt_result['n_trainable'], 'total_parameters': adapt_result['n_total'], 'training_pairs': adapt_result['n_pairs'], 'best_epoch': adapt_result['best_epoch'], 'selection': adapt_result['selection'], 'selection_split': 'validation', 'seconds': adapt_seconds}})"
            ),
        },
        {
            "md": (
                "**What to notice:** epoch 0 is labelled the frozen model, the validation CIDEr-D does not climb steadily, and "
                "the kept epoch is the one with the highest validation score.\n\n"
                "<details><summary>Check your reasoning</summary>No. In the recorded runs of the previous notebook version the "
                "validation CIDEr-D went 0.675 → 0.699 → 0.656 → 0.709 → 0.716 over epochs 0–4: it fell in epoch 2 and rose "
                "again, and epoch 4 was kept. Forty photographs give a noisy score, so a single epoch's dip is not a trend. If "
                "the score had never risen above epoch 0, the rule would have kept epoch 0 — the frozen weights — and that would "
                "be a legitimate result, not an error (Section 10 shows one).</details>\n\n"
                "## 8. Held-out evaluation\n\n"
                "In this run the test photographs were never used for training or epoch selection, and no test image appears in "
                "the training or validation splits. The default hyperparameters, however, were chosen in the build record by "
                "their test score (Section 7), so read the delta below as **optimistic**: it is the gain of a configuration that "
                "was picked because it gained on these photographs. The adapted model is scored exactly as the frozen model was "
                "in Section 6, the four systems are put side by side on all four metrics, and the per-category CIDEr-D is "
                "repeated. Read it in this order: **CIDEr-D** first (the consensus metric the epoch was selected on, and the one "
                "that rewards the corpus's own vocabulary), then BLEU-4 and ROUGE-L, which can move the other way when the "
                "adapted captions get longer. The cell prints a verdict — *improved*, *not improved*, or *the selector kept "
                "epoch 0* — and carries on either way: a flat or negative result from an experiment is a result to read, not an "
                "error, and the export in Section 9 still runs. It also keeps a **run history** for this session, one row per "
                "pass through Section 8, so an experiment can be compared with the default run (Section 10). Seventy photographs "
                "from one seeded split of one corpus give **no dispersion estimate**; the deltas are sample-sanity evidence that "
                "the adaptation contract works, not a benchmark, and a gain on VizWiz says nothing about your photographs until "
                "you measure it there.\n\n"
                "**Predict before running:** if CIDEr-D rises, will BLEU-4 rise with it? Will the gain be spread evenly over the "
                "`text` and `no-text` photographs?"
            ),
            "code": (
                "adapted_test = pipe.evaluate(test_records, max_new_tokens=CAPTION_MAX_TOKENS)\n"
                "adapted_val = pipe.evaluate(val_records, max_new_tokens=CAPTION_MAX_TOKENS)\n"
                "adapted_predictions = {{r['id']: model_caption(pipe)(r) for r in test_records}}\n"
                "adapted_fields = by_category(lambda record: adapted_predictions[record['id']], test_records)\n"
                "comparison = {{metric: {{'constant': round(baseline_constant[metric], 3), 'neighbour': round(baseline_neighbour[metric], 3), 'frozen': round(frozen_test[metric], 3), 'adapted': round(adapted_test[metric], 3)}} for metric in METRICS}}\n"
                "comparison['mean_words'] = {{'constant': round(baseline_constant['mean_words'], 1), 'neighbour': round(baseline_neighbour['mean_words'], 1), 'frozen': round(frozen_test['mean_words'], 1), 'adapted': round(adapted_test['mean_words'], 1)}}\n"
                "comparison['delta_vs_frozen'] = {{metric: round(adapted_test[metric] - frozen_test[metric], 3) for metric in METRICS}}\n"
                "comparison['by_category'] = {{category: {{'n': frozen_fields[category]['n'], 'constant': constant_fields[category]['cider_d'], 'frozen': frozen_fields[category]['cider_d'], 'adapted': adapted_fields[category]['cider_d']}} for category in frozen_fields}}\n"
                "for key, row in comparison.items():\n"
                "    print({{key: row}})\n"
                "for record in test_records[:3]:\n"
                "    print({{'category': record['category'], 'frozen': frozen_predictions[record['id']], 'adapted': adapted_predictions[record['id']], 'references': reference_captions(record)[:2]}})\n"
                "delta_cider = adapted_test['cider_d'] - frozen_test['cider_d']\n"
                "if adapt_result['best_epoch'] == 0:\n"
                "    verdict = f'the selector kept epoch 0 (the frozen weights): no epoch beat the frozen validation CIDEr-D, so the adapted model is the frozen model and the test delta is {{delta_cider:.3f}}'\n"
                "elif delta_cider > 0:\n"
                "    verdict = f'improved: the adapted test CIDEr-D is {{delta_cider:.3f}} above the frozen one (optimistic for the default settings, which were chosen on this split)'\n"
                "else:\n"
                "    verdict = f'not improved: the adapted test CIDEr-D is {{delta_cider:.3f}} relative to the frozen one (read it; the notebook carries on)'\n"
                "print({{'best_epoch': adapt_result['best_epoch'], 'verdict': verdict}})\n"
                "run_history = globals().get('run_history', [])\n"
                "run_history.append({{'run': len(run_history) + 1, 'data': 'BYOD' if USE_BYOD else 'sample', 'layers': TRAINABLE_DECODER_LAYERS, 'epochs': EPOCHS, 'learning_rate': LEARNING_RATE, 'best_epoch': adapt_result['best_epoch'], 'frozen_cider_d': round(frozen_test['cider_d'], 3), 'adapted_cider_d': round(adapted_test['cider_d'], 3), 'delta': round(delta_cider, 3)}})\n"
                "print(f\"{{'run':>3}} {{'data':>6}} {{'layers':>6}} {{'epochs':>6}} {{'lr':>8}} {{'best':>4}} {{'frozen':>7}} {{'adapted':>7}} {{'delta':>7}}\")\n"
                "for h in run_history:\n"
                "    print(f\"{{h['run']:>3}} {{h['data']:>6}} {{h['layers']:>6}} {{h['epochs']:>6}} {{h['learning_rate']:>8g}} {{h['best_epoch']:>4}} {{h['frozen_cider_d']:>7.3f}} {{h['adapted_cider_d']:>7.3f}} {{h['delta']:>7.3f}}\")\n"
                "evaluation_report_payload = {{\n"
                "    'model': {{'id': MODEL_ID, 'revision': MODEL_REVISION, 'key': MODEL_KEY}},\n"
                "    'data_source': data_source,\n"
                "    'dataset_digests': {{name: manifest['digest'] for name, manifest in dataset_manifests.items()}},\n"
                "    'splits': disjoint,\n"
                "    'categories': categories,\n"
                "    'max_new_tokens': CAPTION_MAX_TOKENS,\n"
                "    'baselines': {{'constant_caption': baseline_constant, 'colour_neighbour': baseline_neighbour}},\n"
                "    'frozen_test': frozen_test,\n"
                "    'validation_metrics': adapted_val,\n"
                "    'test_metrics': adapted_test,\n"
                "    'comparison': comparison,\n"
                "    'verdict': verdict,\n"
                "    'selection': {{'metric': 'validation CIDEr-D', 'split': 'validation', 'best_epoch': adapt_result['best_epoch'], 'default_hyperparameters_chosen_on': 'the test split, in the build-record sweep (see MODEL_CARD.md); the default-settings test delta is optimistic'}},\n"
                "    'adaptation': {{k: v for k, v in adapt_result.items() if k not in ('history', 'trainable_names')}},\n"
                "    'history': adapt_result['history'],\n"
                "    'adaptation_seconds': adapt_seconds,\n"
                "}}\n"
                "with open('outputs/{stem}_evaluation_report.json', 'w', encoding='utf-8') as f:\n"
                "    json.dump(evaluation_report_payload, f, indent=2, ensure_ascii=False)\n"
                "print({{'report': 'outputs/{stem}_evaluation_report.json'}})"
            ),
        },
        {
            "md": (
                "**What to notice:** the delta row, the mean caption length, the per-category line, the verdict and the run "
                "history.\n\n"
                "<details><summary>Check your reasoning</summary>No to both. In the recorded runs of the previous notebook "
                "version CIDEr-D rose 0.590 → 0.629 while BLEU-4 fell 0.213 → 0.190 and the mean caption grew from 8.9 to 11.2 "
                "words. The adapted decoder writes longer sentences in the corpus's style (naming what is held and where): "
                "CIDEr-D rewards the n-grams the five references agree on, while BLEU-4's precision drops as every extra word is "
                "another chance to miss. The gain sat on the `no-text` photographs (0.525 → 0.615) while the `text` ones stayed "
                "flat (0.638 → 0.639): the adapted model describes objects and scenes better but reads no more labels. Remember "
                "that 0.039 is the gain of a default chosen on this split (Section 7) with no dispersion estimate: it shows the "
                "contract works, not by how much the model improved.</details>\n\n"
                "## 9. Re-caption the drawn scenes, export the adapter and reload it\n\n"
                "The three scenes from Section 5 are captioned again by the adapted model — drawings, a different image "
                "family from the photographs it was tuned on, so this is a small look at what the adaptation did *outside* its "
                "corpus; a different caption here is a finding to record, not a failure. Both caption sets are written as CSV, "
                "and the keyword observations are repeated.\n\n"
                "`pipe.save_artifact` writes the trained tensors — the caption decoder's last two blocks and its head transform "
                "and bias by default, about 78 MB — as `adapter.safetensors`, with a `manifest.json` recording the artifact "
                "format, the base model id and revision, the digest of the base `pytorch_model.bin`, the tensor names, the file "
                "size and SHA-256, the training configuration, the kept epoch and the epoch history (OUT8). When the selector "
                "kept epoch 0 the exported tensors equal the base model's, and the manifest says so through `best_epoch: 0`. "
                "`BlipCaptioningPipeline.from_artifact` re-verifies the base snapshot, checks the artifact manifest, its digest "
                "and its exact tensor set **before** deserialising, refuses any tensor that is not a caption-decoder tensor, and "
                "overlays the tensors onto a freshly loaded base — a new object from files, not the in-memory model (VER2). The "
                "cell checks for identical captions on up to eight test photographs (VER4) and stops with an explanation if they "
                "differ. Under BYOD `result.json` records your upload in place of the VizWiz corpus block.\n\n"
                "**Predict before running:** will the adapted model now name the orange in the fruit drawing?"
            ),
            "code": (
                "import csv\n\n"
                "adapted_results = []\n"
                "for name, image, keywords in scenes:\n"
                "    result = pipe.caption(image, max_new_tokens=CAPTION_MAX_TOKENS)\n"
                "    result['image'] = name\n"
                "    result['keyword_hits'] = keyword_hits(result['caption'], keywords)\n"
                "    adapted_results.append(result)\n"
                "adapted_scene = evaluation_report(adapted_results, None, sample_kind='synthetic')\n"
                "for before, after in zip(results, adapted_results, strict=True):\n"
                "    print({{'image': before['image'], 'frozen': before['caption'], 'adapted': after['caption'], 'keywords_after': after['keyword_hits']}})\n"
                "with open('outputs/{stem}_captions.csv', 'w', encoding='utf-8', newline='') as handle:\n"
                "    writer = csv.writer(handle)\n"
                "    writer.writerow(['image', 'frozen_caption', 'adapted_caption', 'adapted_new_tokens', 'expected_keywords'])\n"
                "    for before, after, keywords in zip(results, adapted_results, expected_keywords, strict=True):\n"
                "        writer.writerow([before['image'], before['caption'], after['caption'], after['new_tokens'], ' | '.join(keywords)])\n\n"
                "artifact_dir = Path('outputs/{stem}_adapter')\n"
                "shutil.rmtree(artifact_dir, ignore_errors=True)\n"
                "pipe.save_artifact(artifact_dir, metadata={{'tutorial': '{stem}', 'data_source': data_source}})\n"
                "artifact_manifest = json.loads((artifact_dir / 'manifest.json').read_text(encoding='utf-8'))\n"
                "print({{'artifact': str(artifact_dir), 'format': artifact_manifest['format'], 'tensors': len(artifact_manifest['tensors']), 'bytes': artifact_manifest['files'][0]['bytes'], 'sha256': artifact_manifest['files'][0]['sha256'][:16] + '...', 'best_epoch': artifact_manifest['adapter']['best_epoch']}})\n\n"
                "reloaded = BlipCaptioningPipeline.from_artifact(artifact_dir, weights_dir=WEIGHTS_DIR, device=pipe.device)\n"
                "before = [model_caption(pipe)(r) for r in test_records[:8]]\n"
                "after = [model_caption(reloaded)(r) for r in test_records[:8]]\n"
                "parity = {{'identical_captions': sum(a == b for a, b in zip(before, after, strict=True)), 'of': len(before)}}\n"
                "print({{'reload_parity': parity, 'reloaded_best_epoch': reloaded.adapter['best_epoch']}})\n"
                "reloaded = None  # free the second copy of the model before any re-run\n"
                "gc.collect()\n"
                "if parity['identical_captions'] != parity['of']:\n"
                "    raise RuntimeError(f'Reload parity failed: {{parity}}. The saved adapter does not reproduce the model that was evaluated in Section 8. Re-run from Section 7 (it reloads the pretrained model before adapting), or restart the session and choose Run all.')\n\n"
                "weight_entry = next(entry for entry in MANIFEST['files'] if entry['path'] == WEIGHT_FILE)\n"
                "result_payload = {{\n"
                "    'notebook_source': NOTEBOOK_SOURCE,\n"
                "    'repository_revision': NOTEBOOK_SOURCE['repository_revision'],\n"
                "    'model_id': MODEL_ID,\n"
                "    'model_revision': MODEL_REVISION,\n"
                "    'model_license': MODEL_LICENSE,\n"
                "    'snapshot': {{'path': str(WEIGHTS_DIR), 'files': snapshot['files'], 'total_bytes': snapshot.get('total_bytes'), 'fetched_this_run': fetched, 'weight_file': WEIGHT_FILE, 'weight_format': 'pytorch_model.bin pickle, digest-verified, weights_only=True', 'weight_sha256': weight_entry['sha256'], 'hosted_tf_weight_file_not_loaded': HOSTED_TF_WEIGHT_FILE}},\n"
                "    'data_source': data_source,\n"
                "    'corpus': None if USE_BYOD else {{'name': CORPUS_NAME, 'repo': CORPUS_REPO, 'revision': CORPUS_REVISION, 'release': CORPUS_RELEASE, 'license': CORPUS_LICENSE, 'text_columns': list(CORPUS_TEXT_COLUMNS), 'file': CORPUS_FILE, 'pinned_images': len(IMAGE_PINS)}},\n"
                "    'byod': byod,\n"
                "    'splits': disjoint,\n"
                "    'inference_contract': {{'input_manifest': input_manifest, 'sanity_checks': checks, 'scenes': {{'names': scene_names, 'sizes': [list(image.size) for image in scene_images], 'rgb_sha256': scene_digests, 'expected_keywords': expected_keywords}}, 'items': [{{k: r[k] for k in ('image', 'caption', 'new_tokens', 'truncated', 'keyword_hits', 'seconds')}} for r in results], 'frozen_report': frozen_scene, 'adapted_items': [{{k: r[k] for k in ('image', 'caption', 'new_tokens', 'truncated', 'keyword_hits')}} for r in adapted_results], 'adapted_report': adapted_scene}},\n"
                "    'adaptation': {{'best_epoch': adapt_result['best_epoch'], 'selection': adapt_result['selection'], 'learning_rate': LEARNING_RATE, 'epochs': EPOCHS, 'trainable_decoder_layers': TRAINABLE_DECODER_LAYERS, 'batch_size': BATCH_SIZE}},\n"
                "    'verdict': verdict,\n"
                "    'comparison': comparison,\n"
                "    'artifact': {{'dir': str(artifact_dir), 'sha256': artifact_manifest['files'][0]['sha256'], 'bytes': artifact_manifest['files'][0]['bytes'], 'tensors': len(artifact_manifest['tensors'])}},\n"
                "    'reload_parity': parity,\n"
                "    'runtime': {{'python': platform.python_version(), 'torch': torch.__version__, 'transformers': transformers.__version__, 'device': pipe.device, 'dtype': 'float32', 'source': pipe.source}},\n"
                "}}\n"
                "with open('outputs/{stem}_result.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump(result_payload, handle, indent=2, ensure_ascii=False)\n"
                "print(sorted(os.listdir('outputs')))"
            ),
        },
    ],
    "closing": (
        "**What to notice:** which scene captions changed, the artifact's tensor count and size, and the reload-parity line.\n\n"
        "<details><summary>Check your reasoning</summary>In the recorded runs of the previous notebook version, yes: the "
        "adapted model captioned the fruit drawing `an apple and an orange on a white background`, where the frozen model had "
        "called the orange a second apple, and kept the house and beach captions with a location phrase appended. That is one "
        "drawing of evidence, not a measurement: the adaptation trained on photographs, and a change on a cartoon can go either "
        "way. The artifact held 57 tensors (78,112,280 bytes) and reload parity was 8/8: the exported adapter is the model that "
        "was evaluated.</details>\n\n"
        "## 10. Your turn — change one thing: a higher learning rate\n\n"
        "Optional; **Predict → Change → Run → Observe → Explain**. It retrains, so it takes about as long as Section 7 did.\n\n"
        "1. **Predict:** with a learning rate five times higher (`5e-5` instead of `1e-5`), will validation CIDEr-D rise "
        "faster, rise and then fall, or fall from the first epoch? Which epoch will the selector keep? Write your guess down, "
        "next to the default run's numbers in the Section 8 run history.\n"
        "2. **Change:** in Section 7 set `LEARNING_RATE = 5e-5`. Change nothing else.\n"
        "3. **Run:** select the Section 7 cell and choose **Runtime → Run after**. Section 7 reloads the pretrained model "
        "before adapting, Section 8 compares against the same Section 6 frozen score and adds a row to the run history, and "
        "Section 9 exports and reloads the new adapter.\n"
        "4. **Observe:** in Section 7, epoch 0 shows the *frozen* validation CIDEr-D again (about 0.675, not the adapted "
        "0.716), then watch the training loss and the validation score; in Section 8, read the verdict and compare the two "
        "rows of the run history; in Section 9, read `best_epoch` in the artifact line.\n"
        "5. **Explain:** in one sentence, why did the selector keep the epoch it kept, and what does that tell you about "
        "fine-tuning on 208 photographs?\n\n"
        "<details><summary>Check your reasoning</summary>It falls from the first epoch, and the selector keeps epoch 0. In a "
        "local Windows CPU check of this notebook version (real weights, float32; the same numbers as the review of the "
        "previous version) the validation CIDEr-D went 0.675 → 0.628 → 0.594 → 0.587 → 0.528 while the training loss kept falling: the decoder "
        "fits the 889 training captions (overfitting) and drifts away from captions that suit new photographs. No epoch beat "
        "the frozen validation score, so the rule kept epoch 0, the adapted test CIDEr-D equalled the frozen one (0.5895), and "
        "Section 8's verdict says so instead of stopping. That is the selector doing its job: validation-based selection is "
        "what protects you from a bad setting. If epoch 0 did not show about 0.675, the model was not reset — restart and "
        "**Run all**.</details>\n\n"
        "## Interpretation and limits\n\n"
        "The frozen model is already a competent captioner on photographs it never saw — far above the two non-neural "
        "baselines — and a bounded fine-tuning of the caption decoder's last two blocks and head on 208 VizWiz photographs "
        "moved the consensus metric by a few hundredths of CIDEr-D on an image-disjoint test split (0.590 → 0.629 in the "
        "recorded runs of the previous notebook version, on the `no-text` photographs rather than the ones with labels) while "
        "lengthening the sentences toward the corpus's style, with a 78 MB adapter that reloads to identical captions. That "
        "is the claim: the adaptation contract works end to end on a real out-of-distribution captioning corpus, and the "
        "numbers it produces are read on four metrics and per category against two non-neural baselines and the frozen model "
        "rather than in isolation. It is a smaller effect than a task the base model cannot do at all would show, and the "
        "notebook says so.\n\n"
        "The size of that gain is also **optimistic**: the default learning rate and epoch count were chosen in the build "
        "record by comparing configurations on these same 70 test photographs, so the test split is not independent evidence "
        "for the default settings. Within a run, validation alone chooses the epoch. The test split is 70 photographs from one "
        "seeded draw of one row group of one shard of one corpus, the validation split that picks the epoch is 40, the "
        "metrics are four reference-based scores (own pure-Python implementations of the `coco-caption` definitions, with "
        "CIDEr-D's document frequencies from the evaluated set — so its absolute value is not comparable to leaderboard numbers "
        "computed on the full validation set — and none a human judgement), and a higher learning rate overfits this little "
        "data within one epoch, which the validation-based selector reports by keeping epoch 0 (Section 10). So a gain here "
        "says the contract works, not that the adapted model is better on your photographs, that it reads the labels it now "
        "mentions, or that its captions are faithful — it still generates a sentence for every image, and it can be wrong "
        "fluently. Fine-tuning on a narrow corpus can also erode the model elsewhere; the drawn scenes re-captioned in "
        "Section 9 are three images of evidence about that, not a measurement.\n\n"
        "Four things to carry to real data. **Baselines first:** the constant-caption and colour-neighbour baselines and "
        "the frozen model's score on *your* references are the numbers to read before any adapted one, per category and on "
        "CIDEr-D. **Selection:** choose settings on validation only, and keep a test split you look at once. **Leakage:** keep "
        "every record on an image in one split (the contract does this) and split by photographer or session when your images "
        "come from few sources, never at random over near-duplicate frames. **References:** every reference caption is a "
        "training target; a corpus with one caption per image trains the model on one annotator's phrasing, and CIDEr-D with "
        "a single reference rewards that phrasing rather than a consensus.\n\n"
        "Successful execution proves that the recorded repository revision's pipeline modules, carried in this standalone "
        "notebook, can acquire and digest-verify the pinned model snapshot, fetch and digest-verify the captions and "
        "photographs of a real captioning corpus, validate the demonstrated dataset contract without leakage, execute the "
        "inference contract and a bounded fine-tuning, evaluate against two trivial baselines and the frozen model on an "
        "image-disjoint split, and emit the shown machine-readable artifacts — without the repository being reachable. It "
        "does **not** establish benchmark superiority, caption quality on any other population or camera, or production "
        "fitness.\n\n"
        "**Optional experiments (they do not affect the default path).** Each one changes one form field; note the numbers "
        "you want to compare first (the Section 8 run history keeps one row per pass). In Colab, **Runtime → Run after** runs "
        "the selected cell and every cell below it; Sections 5, 6 and 7 reload the pretrained model before they use it, so no "
        "experiment inherits an earlier adaptation.\n\n"
        "- **A higher learning rate:** Section 10.\n"
        "- **Fewer trainable blocks:** set `TRAINABLE_DECODER_LAYERS = 1` in Section 7, select Section 7 and choose **Run "
        "after**; compare the artifact size and the held-out score.\n"
        "- **More epochs:** set `EPOCHS = 6` in Section 7, select Section 7 and choose **Run after**; watch whether validation "
        "CIDEr-D keeps rising or turns (the best epoch is kept either way).\n"
        "- **Another split:** change `SPLIT_SEED` in Section 4, select Section 4 and choose **Run after**; read how much the "
        "frozen and adapted scores move with a different draw of 70 test photographs.\n"
        "- **Your own photographs:** BYOD (Section 4, then **Run after**); read the two baselines and the frozen score before "
        "the adapted number.\n\n"
        "## Troubleshooting\n\n"
        "- **Section 1 stops with \"needs a Linux x86_64 runtime\".** The locked environment is built from manylinux wheels. "
        "Use Google Colab, Kaggle or a Linux Jupyter server; Windows and macOS kernels are not supported.\n"
        "- **Section 1 fails while downloading** (`uv` wheel, Python build or packages). The runtime needs PyPI and the "
        "python-build-standalone download; run the cell again once the network is back. A \"size/SHA-256\" or \"does not "
        "match its digest\" error means a file was altered: do not edit the cell, regenerate the notebook from the "
        "repository.\n"
        "- **\"The isolated environment's Python process exited\".** Usually the runtime ran out of memory. Restart the "
        "session and choose **Run all**; on CPU, close other notebooks first.\n"
        "- **Out of disk, or the checkpoint download stops.** The locked install, the 990 MB checkpoint and the 84 MB of "
        "photographs need a few GB of free space. Start a fresh runtime, or delete `dimer_isolated_env/` and `weights/` from "
        "an earlier attempt.\n"
        "- **A digest or size mismatch in Section 3 or 4.** A download was incomplete or altered; the notebook refuses it "
        "rather than continuing. Run the cell again; never edit the manifest or the image pins.\n"
        "- **BYOD is refused in Section 4.** The message names what to fix: a split left with too few records (at least 12 "
        "records on 12 different images), no or several records files, an image path that does not exist relative to the "
        "records file, an empty caption, a duplicate id, a zip over the member or size limit, or a member outside the upload "
        "folder. Fix the zip and run Section 4 with **Run after** again. An empty or cancelled upload asks you to choose a "
        "file or set `BYOD_PATH`.\n"
        "- **Section 8 says \"not improved\" or \"the selector kept epoch 0\".** Not an error: under these settings no "
        "adaptation beat the frozen model on validation, or the kept epoch did not beat it on test. Read the epoch history in "
        "Section 7; the export and reload in Section 9 still run.\n"
        "- **Reload parity fails in Section 9.** The saved adapter does not reproduce the evaluated model. Re-run from "
        "Section 7 (it reloads the pretrained model first), or restart the session and choose **Run all**.\n"
        "- **Numbers differ slightly from the recorded runs.** CPU and GPU arithmetic differ, and because decoding is "
        "autoregressive one different token changes the rest of a caption; a few thousandths of CIDEr-D between a T4 and a "
        "CPU run are expected. Larger differences on the default settings mean a form field was changed.\n"
        "- **You re-ran the routing cell in Section 1.** It starts a new isolated process and discards every variable "
        "created so far; choose **Run all** again.\n\n"
        "## Glossary\n\n"
        "- **Caption / reference caption:** the sentence the model generates for an image, and a human-written sentence it "
        "is compared with (VizWiz has up to five per photograph).\n"
        "- **Greedy decoding:** generating each next token as the single most likely one; reproducible, but not a quality "
        "guarantee.\n"
        "- **Token budget (`max_new_tokens`):** the most tokens the model may generate; `truncated` says the budget ran out.\n"
        "- **BLEU-4:** the share of the caption's 1- to 4-word sequences that appear in the references, with a penalty for "
        "captions shorter than the references.\n"
        "- **ROUGE-L:** how long a common word sequence the caption shares with its best-matching reference, as an "
        "F-measure.\n"
        "- **CIDEr-D:** agreement with the n-grams the references share, each weighted by how rare it is across the evaluated "
        "set (TF-IDF); higher is better and it can exceed 1.\n"
        "- **Document frequency:** in how many images' references an n-gram appears; common n-grams count for less in "
        "CIDEr-D.\n"
        "- **Baseline:** a system with no model (here a constant caption and a colour lookup) that shows what any useful "
        "model must beat.\n"
        "- **Fine-tuning / trainable blocks:** further training on labelled examples; only the named decoder blocks may "
        "change, the rest stay frozen.\n"
        "- **Learning rate:** how large each training step is; too large and the model overfits a small dataset quickly.\n"
        "- **Epoch / validation selection:** one pass over the training pairs; the epoch kept is the one with the highest "
        "validation CIDEr-D (epoch 0 = the frozen model).\n"
        "- **Training / validation / test split:** photographs used to train, to choose the epoch, and to report the final "
        "result once; split by image so no photograph is in two splits.\n"
        "- **Optimistic estimate:** a test score of a configuration that was chosen by looking at that same test score.\n"
        "- **Adapter / reload parity:** the saved trained tensors, and the check that a pipeline rebuilt from them gives the "
        "same captions.\n\n"
        "## Conclusion (your notes)\n\n"
        "Optional personal notes, not a required submission. Complete each sentence from your own run:\n\n"
        "- On these test photographs the constant caption reached a CIDEr-D of ___, the pretrained model ___ and the adapted "
        "model ___; the verdict was ___.\n"
        "- The gain sat mostly on the ___ photographs, and BLEU-4 moved ___ because ___.\n"
        "- With a learning rate of 5e-5 (Section 10) the selector kept epoch ___, because ___.\n"
        "- The test gain is optimistic because ___; before trusting this adaptation on my own photographs I would measure ___ "
        "on ___.\n\n"
        "## References\n\n"
        "- Repository README: https://github.com/kurtvalcorza/blip-captioning-pipeline/blob/main/README.md\n"
        "- Repository model card: https://github.com/kurtvalcorza/blip-captioning-pipeline/blob/main/MODEL_CARD.md\n"
        "- Weight provenance: https://github.com/kurtvalcorza/blip-captioning-pipeline/blob/main/docs/WEIGHTS.md\n"
        "- Upstream model (Salesforce, BSD-3-Clause): https://huggingface.co/{MODEL_ID}\n"
        "- Upstream code: https://github.com/salesforce/BLIP\n"
        "- BLIP: Bootstrapping Language-Image Pre-training for Unified Vision-Language Understanding and Generation (Li et al., 2022): https://arxiv.org/abs/2201.12086\n"
        "- Captioning Images Taken by People Who Are Blind (Gurari et al., ECCV 2020; VizWiz-Captions, CC BY 4.0): https://arxiv.org/abs/2002.08565 — data: https://vizwiz.org/tasks-and-datasets/image-captioning/\n"
        "- BLEU: a Method for Automatic Evaluation of Machine Translation (Papineni et al., 2002): https://aclanthology.org/P02-1040/\n"
        "- ROUGE: A Package for Automatic Evaluation of Summaries (Lin, 2004): https://aclanthology.org/W04-1013/\n"
        "- CIDEr: Consensus-based Image Description Evaluation (Vedantam et al., 2015): https://arxiv.org/abs/1411.5726\n"
        "- DIMER Notebook Specification 2.2 and Model Card Specification 1.1 (fleet specs in the ml-worker repository)"
    ),
}
